Create num_islands.java
Gupta-Nikhil85/LC-Google-Pr pull request #15
Opened 2022-10-03 13:20 UTC by anirudh0806

2022-10-03 17:14 UTC, Gupta-Nikhil85 commented on Number of Islands/num_islands.java
> +class Solution
Do include the problem link in here as a comment

2022-10-03 17:15 UTC, Gupta-Nikhil85 requested changes
Please do include the question's link as a comment at the top of file.

2022-10-04 06:27 UTC, anirudh0806 commented
I have added the link for the problem as a comment. Please check. Make me an assignee too.

2022-10-04 13:24 UTC, Gupta-Nikhil85 approved these changes

2022-10-04 13:24 UTC, merged